# Generated by Django 4.1.5 on 2023-02-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_channel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("student_email", models.EmailField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
